# Generated by Django 6.0.5 on 2026-05-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pays_rattachement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avions/')),
                ('longueur_piste_necessaire', models.IntegerField(help_text='En mètres')),
            ],
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('longueur', models.IntegerField(help_text='Longueur en mètres')),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes', to='TraficAerien.aeroport')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraficAerien.compagnie')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraficAerien.typeavion')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=100)),
                ('date_heure_depart', models.DateTimeField()),
                ('date_heure_arrivee', models.DateTimeField()),
                ('aeroport_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_arrivee', to='TraficAerien.aeroport')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_depart', to='TraficAerien.aeroport')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TraficAerien.avion')),
            ],
        ),
    ]
